#ifndef CaPTkGetModalityAndDescription_h
#define CaPTkGetModalityAndDescription_h

// The following header file is generated by CMake and thus it's located in
// the build directory. It provides an export macro for classes and functions
// that you want to be part of the public interface of your module.
#include <MitkCaPTkCommonExports.h>

#include <mitkBaseData.h>

#include <string>

namespace captk
{
/** \brief Get modality and description from BaseData
 * 
 * Note: mitk::Image::Pointer and mitk::LabelSetImage::Pointer can be cast to the input variable
 * \param data the input data
 * \param modality the modality would be populated here
 * \param description the description (i.e. acquisition protocol) would be populated here
 * \return true if operation was successful
*/
MITKCAPTKCOMMON_EXPORT bool GetModalityAndDescription(
    mitk::BaseData::Pointer data, 
    std::string& modality, 
    std::string& description);
}

#endif // ! CaPTkGetModalityAndDescription_h