#ifndef CaPTkRecurrenceTrainCheckInputStructure_h
#define CaPTkRecurrenceTrainCheckInputStructure_h

// The following header file is generated by CMake and thus it's located in
// the build directory. It provides an export macro for classes and functions
// that you want to be part of the public interface of your module.
#include <MitkCaPTkRecurrenceExports.h>

namespace captk 
{

MITKCAPTKRECURRENCE_EXPORT bool RecurrenceTrainCheckInputStructure(
    QSharedPointer<captk::Cohort> cohort,
    std::string& errorMessage
);

MITKCAPTKRECURRENCE_EXPORT bool RecurrenceInferenceCheckInputStructure(
    QSharedPointer<captk::Cohort> cohort,
    std::string& errorMessage,
    const std::vector<std::tuple<QString, QString>> requiredImageTypes
);

namespace internal
{
    MITKCAPTKRECURRENCE_EXPORT bool RecurrenceCheckInputStructure(
        QSharedPointer<captk::Cohort> cohort,
        std::string& errorMessage,
        const std::vector<std::tuple<QString, QString>> requiredImageTypes
    );
}

}

#endif // ! CaPTkRecurrenceTrainCheckInputStructure_h