#ifndef CaPTkRecurrenceInference_h
#define CaPTkRecurrenceInference_h

// The following header file is generated by CMake and thus it's located in
// the build directory. It provides an export macro for classes and functions
// that you want to be part of the public interface of your module.
#include <MitkCaPTkRecurrenceExports.h>

namespace captk 
{

MITKCAPTKRECURRENCE_EXPORT bool Inference(
        const std::string subjectDirPath, 
        const std::string modelDirPath,
        const std::string outputDirPath,
        std::string& errorMessage
);

}

#endif // ! CaPTkRecurrenceInference_h