#ifndef CaPTkRecurrenceTrain_h
#define CaPTkRecurrenceTrain_h

// The following header file is generated by CMake and thus it's located in
// the build directory. It provides an export macro for classes and functions
// that you want to be part of the public interface of your module.
#include <MitkCaPTkRecurrenceExports.h>

namespace captk 
{

MITKCAPTKRECURRENCE_EXPORT bool Train(
        const std::string subjectDirPath, 
        const std::string outputModelDirPath,
        std::string& errorMessage
);

}

#endif // ! CaPTkRecurrenceTrain_h